server:
  port: 80
spring:
  application:
    name: mall-admin-service
  cloud:
    nacos:
      discovery:
        namespace: 19f31a9a-62bf-49dd-bfbd-829103d78ea4
        group: DEFAULT_GROUP
        server-addr: localhost:8848
mall:
  jwt:
    tokenHeader: Authorization
    secret: atguigu_2019
    expiration: 604800
    tokenHead: Bearer